services:
  postgres:
    build: 
      context: .
      dockerfile: Dockerfile.postgres
    platform: linux/arm64
    env_file:
      - .env.postgres
    environment:
      - TZ=UTC
    restart: unless-stopped
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '16'
          memory: 76G
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d neynar_parquet_importer"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - neynar-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
    shm_size: '32gb'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    stop_grace_period: 120s

  app1:
    build:
      context: .
      dockerfile: Dockerfile.parquet
    tty: true
    stdin_open: true
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.v2
    environment:
      - INTERACTIVE_DEBUG=true
      - COLUMNS=250
      - LINES=75
      - TZ=UTC
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '7'
          memory: 64G
    volumes:
      - parquet-files:/app/data/parquet
      - $HOME/.aws:/root/.aws:delegated
    networks:
      - neynar-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"

  app2:
    build:
      context: .
      dockerfile: Dockerfile.parquet
    tty: true
    stdin_open: true
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.v3
    environment:
      - INTERACTIVE_DEBUG=true
      - COLUMNS=250
      - LINES=75
      - TZ=UTC
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 32G
    volumes:
      - parquet-files:/app/data/parquet
      - $HOME/.aws:/root/.aws:delegated
    networks:
      - neynar-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"

volumes:
  postgres_data:
  parquet-files:

networks:
  neynar-network:
    name: neynar-network
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500
