services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example_neynar_parquet_importer
    restart: unless-stopped
    ports:
      - "15432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./data/app:/usr/src/app/data
      - $HOME/.aws:/root/.aws
